--
-- PostgreSQL database cluster dump
--

-- Started on 2025-02-15 14:54:34

SET default_transaction_read_only = off;

SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;

--
-- Roles
--

CREATE ROLE postgres;
ALTER ROLE postgres WITH SUPERUSER INHERIT CREATEROLE CREATEDB LOGIN REPLICATION BYPASSRLS PASSWORD 'SCRAM-SHA-256$4096:o9BYDRRokvz3vu68ru8T2w==$qanTd4B7Ci0Nru3CqKDJ7r4JkkdLmqhpUKZs+RhoUIM=:2DPi6zbspJ+mUahoJSeV3Wb8Ix9QS5Ku+GERQJ1gzAU=';
CREATE ROLE u_ccl;
ALTER ROLE u_ccl WITH SUPERUSER INHERIT CREATEROLE CREATEDB LOGIN NOREPLICATION BYPASSRLS PASSWORD 'SCRAM-SHA-256$4096:LwcEH9b7fHceQoUwzhZawg==$5s13FOVOT/IO4dmfTo5QsLXQtA0MBrB5nQdUUq/p27I=:kgxycgUa+KuKRGOdelvaRju0bLqHN46WT079qqi9l9A=';

--
-- User Configurations
--








--
-- Databases
--

--
-- Database "template1" dump
--

\connect template1

--
-- PostgreSQL database dump
--

-- Dumped from database version 17.3
-- Dumped by pg_dump version 17.3

-- Started on 2025-02-15 14:54:34

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

-- Completed on 2025-02-15 14:54:35

--
-- PostgreSQL database dump complete
--

--
-- Database "db_ccl" dump
--

--
-- PostgreSQL database dump
--

-- Dumped from database version 17.3
-- Dumped by pg_dump version 17.3

-- Started on 2025-02-15 14:54:35

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 4795 (class 1262 OID 16388)
-- Name: db_ccl; Type: DATABASE; Schema: -; Owner: u_ccl
--

CREATE DATABASE db_ccl WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'en-US';


ALTER DATABASE db_ccl OWNER TO u_ccl;

\connect db_ccl

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 218 (class 1259 OID 16390)
-- Name: tb_productos; Type: TABLE; Schema: public; Owner: u_ccl
--

CREATE TABLE public.tb_productos (
    id integer NOT NULL,
    nombre character(40) NOT NULL,
    cantidad integer NOT NULL
);


ALTER TABLE public.tb_productos OWNER TO u_ccl;

--
-- TOC entry 217 (class 1259 OID 16389)
-- Name: tb_inventario_id_seq; Type: SEQUENCE; Schema: public; Owner: u_ccl
--

ALTER TABLE public.tb_productos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tb_inventario_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4789 (class 0 OID 16390)
-- Dependencies: 218
-- Data for Name: tb_productos; Type: TABLE DATA; Schema: public; Owner: u_ccl
--

COPY public.tb_productos (id, nombre, cantidad) FROM stdin;
4	Azael                                   	2
9	so                                      	12
10	so1                                     	23
\.


--
-- TOC entry 4796 (class 0 OID 0)
-- Dependencies: 217
-- Name: tb_inventario_id_seq; Type: SEQUENCE SET; Schema: public; Owner: u_ccl
--

SELECT pg_catalog.setval('public.tb_inventario_id_seq', 10, true);


--
-- TOC entry 4642 (class 2606 OID 16394)
-- Name: tb_productos tb_inventario_pkey; Type: CONSTRAINT; Schema: public; Owner: u_ccl
--

ALTER TABLE ONLY public.tb_productos
    ADD CONSTRAINT tb_inventario_pkey PRIMARY KEY (id);


-- Completed on 2025-02-15 14:54:35

--
-- PostgreSQL database dump complete
--

--
-- Database "postgres" dump
--

\connect postgres

--
-- PostgreSQL database dump
--

-- Dumped from database version 17.3
-- Dumped by pg_dump version 17.3

-- Started on 2025-02-15 14:54:35

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

-- Completed on 2025-02-15 14:54:35

--
-- PostgreSQL database dump complete
--

-- Completed on 2025-02-15 14:54:35

--
-- PostgreSQL database cluster dump complete
--

